library(data.table)
data_1 <- read.csv("household_power_consumption.txt",header=T,sep=";",na.strings = NA,stringsAsFactors = FALSE)
TT <- subset(data_1,Date=="1/2/2007")
TU <- subset(data_1,Date=="2/2/2007")
TTU <- rbind(TT,TU)
TTU$Global_active_power <- as.numeric(TTU$Global_active_power)
png(filename = "Plot1.png")
TTU$Global_active_power <- as.numeric(TTU$Global_active_power)
hist(TTU$Global_active_power,xlim = c(0,6),ylim = c(0,1200),breaks= 12,xlab = "Global Active Power (kilowatts)",main = "Global Active Power", col="red")
dev.off()
