library(data.table)
data_1 <- read.csv("household_power_consumption.txt",header=T,sep=";",na.strings = NA,stringsAsFactors = FALSE)
TT <- subset(data_1,Date=="1/2/2007")
TU <- subset(data_1,Date=="2/2/2007")
TTU <- rbind(TT,TU)
TTU$Global_active_power <- as.numeric(TTU$Global_active_power)
TTU$Sl <- c(1:nrow(TTU))

png(filename = "Plot4.png")
par(mfrow=c(2,2),mar=c(4,4,1,1))
plot(TTU$Sl,TTU$Global_active_power,type = "n",xaxt="n",ylab="Global Active Power",xlab="")
lines(TTU$Sl,TTU$Global_active_power)
axis(1,at=c(1,1440,2880),labels = c("Thu","Fri","Sat"))

plot(TTU$Sl,TTU$Voltage,type = "n",xaxt="n",ylab="Voltage",xlab="datetime")
lines(TTU$Sl,TTU$Voltage)
axis(1,at=c(1,1440,2880),labels = c("Thu","Fri","Sat"))

plot(TTU$Sl,TTU$Sub_metering_1,type="n",xaxt="n",,xlab="",ylab="Energy sub metering")
lines(TTU$Sl,TTU$Sub_metering_1)
lines(TTU$Sl,TTU$Sub_metering_2,col="red")
lines(TTU$Sl,TTU$Sub_metering_3,col="blue")
axis(1,at=c(1,1440,2880),labels = c("Thursday","Friday","Saturday"))
legend("topright",legend=c("Sub_metering 1","Sub_metering 2","Sub_metering 3"),col=c("black","red","blue"),lty = 1,lwd=1,bty="n")

plot(TTU$Sl,TTU$Global_reactive_power,type = "n",xaxt="n",ylab="Global Reactive Power",xlab="datetime")
lines(TTU$Sl,TTU$Global_reactive_power )
axis(1,at=c(1,1440,2880),labels = c("Thu","Fri","Sat"))
dev.off()
